title: Fdev210's world
author: Fabiano Vasconcelos Sant'Anna
email: vsantanna.fabiano@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Desenvolvedor web autodidata e entusiasta no assunto. É defensor do uso de softwares livres e fontes de código aberto e acredita no poder da colaboração entre os povos. Vê na tecnologia a saída para muitos problemas da humanidade

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  [GitHub](https://github.com/Fdev210) # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
